-- Persistence for admin column defaults, per-file overrides, and revocable public links.
-- Run this in the Supabase SQL editor before enabling the new endpoints.

create table if not exists public.survei_column_mappings (
  id bigint generated by default as identity primary key,
  id_survei uuid not null,
  key_column text,
  column_mapping jsonb not null default '{}'::jsonb,
  key_mappings jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

create unique index if not exists survei_column_mappings_id_survei_uidx
  on public.survei_column_mappings (id_survei);

create table if not exists public.penyelesaian_mappings (
  id bigint generated by default as identity primary key,
  id_penyelesaian uuid not null,
  key_column text,
  column_mapping jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

create unique index if not exists penyelesaian_mappings_id_penyelesaian_uidx
  on public.penyelesaian_mappings (id_penyelesaian);

create table if not exists public.penyelesaian_shares (
  id bigint generated by default as identity primary key,
  id_penyelesaian uuid not null,
  token_hash text not null unique,
  permission text not null default 'view' check (permission = 'view'),
  allowed_sheets jsonb not null default '[]'::jsonb,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists penyelesaian_shares_active_token_idx
  on public.penyelesaian_shares (token_hash)
  where revoked_at is null;

-- Compatibility migration for a table created before key_mappings was added.
alter table if exists public.survei_column_mappings
  add column if not exists key_mappings jsonb not null default '{}'::jsonb;

create unique index if not exists survei_column_mappings_id_survei_uidx
  on public.survei_column_mappings (id_survei);

create unique index if not exists penyelesaian_mappings_id_penyelesaian_uidx
  on public.penyelesaian_mappings (id_penyelesaian);

alter table public.survei_column_mappings enable row level security;
alter table public.penyelesaian_mappings enable row level security;
alter table public.penyelesaian_shares enable row level security;

-- The API uses the service-role key, so these tables stay inaccessible to anon.
-- Add explicit Supabase policies here if the frontend will query them directly.
